"""
Pure unit tests for app/detection/metadata_scorer.py.

All inputs are plain Python dicts/strings — no image files, no PIL, sub-millisecond per test.
"""

import pytest

from app.detection.metadata_scorer import (
    get_ai_suspicion_score,
    get_forensic_metadata_score,
    get_tiered_signature_score,
)


# ---------------------------------------------------------------------------
# get_tiered_signature_score
# ---------------------------------------------------------------------------


def test_tier1_generator_returns_max_score():
    """Known AI tool name in metadata → score ≈ 0.99."""
    dump = "software: midjourney v6 details"
    score, signals = get_tiered_signature_score(dump, dump)

    assert score >= 0.99
    assert any("midjourney" in s.lower() for s in signals)


def test_tier1_stable_diffusion_detected():
    dump = "generated by stable diffusion xl"
    score, signals = get_tiered_signature_score(dump, dump)

    assert score >= 0.99


def test_tier2_hit_increases_score():
    """Tier-2 technical term → score > 0."""
    dump = "comfyui workflow metadata"
    score, _ = get_tiered_signature_score(dump, dump)

    assert score > 0


def test_no_matches_returns_zero():
    dump = "make: apple model: iphone 14 iso: 400"
    score, signals = get_tiered_signature_score(dump, dump)

    assert score == 0.0
    assert signals == []


# ---------------------------------------------------------------------------
# get_forensic_metadata_score
# ---------------------------------------------------------------------------


def test_rich_camera_exif_high_score():
    """Full iPhone-style EXIF should yield score >= 0.60 (verified human exit)."""
    exif = {
        "Make": "Apple",
        "Model": "iPhone 14 Pro",
        "ISOSpeedRatings": 400,
        "FNumber": 1.78,
        "ExposureTime": 0.008,
        "DateTimeOriginal": "2024:06:15 14:32:00",
        "ColorSpace": 65535,
        "Orientation": 1,
        "SensingMethod": 2,
    }
    score, signals = get_forensic_metadata_score(exif)

    assert score >= 0.60
    assert len(signals) > 0


def test_dslr_exif_high_score():
    """Canon DSLR EXIF with serial numbers → high forensic score."""
    exif = {
        "Make": "Canon",
        "Software": "Capture One 23",
        "ISOSpeedRatings": 800,
        "FNumber": 2.8,
        "ExposureTime": 0.002,
        "DateTimeOriginal": "2023:11:10 09:15:00",
        "BodySerialNumber": "123456789",
        "LensModel": "EF 50mm f/1.4 USM",
        "GPSLatitude": (51.5, 0.0, 0.0),
    }
    score, _ = get_forensic_metadata_score(exif)

    assert score >= 0.60


def test_empty_exif_zero_score():
    score, signals = get_forensic_metadata_score({})

    assert score == 0.0
    assert signals == []


# ---------------------------------------------------------------------------
# get_ai_suspicion_score
# ---------------------------------------------------------------------------


def test_ai_software_field_raises_score():
    exif = {"Software": "Stable Diffusion"}
    score, signals = get_ai_suspicion_score(exif, 0, 0, 0)

    assert score >= 0.40
    assert any("software" in s.lower() or "signature" in s.lower() for s in signals)


def test_ai_typical_dimensions_no_camera_raises_score():
    """1024×1024 with no Make field → dimension check adds score."""
    exif = {}  # no camera provenance
    score, signals = get_ai_suspicion_score(exif, 1024, 1024, 500_000)

    assert score > 0.0
    assert any("1024" in s for s in signals)


def test_phone_portrait_dimensions_reduce_score():
    """750×1334 portrait (9:16) with no Make → phone screenshot, score reduced vs plain 750×750."""
    exif = {}
    score_portrait, _ = get_ai_suspicion_score(exif, 750, 1334, 300_000)
    score_square, _ = get_ai_suspicion_score(exif, 750, 750, 300_000)

    # Portrait phone screenshot should not be penalised as heavily as square AI image
    assert score_portrait <= score_square


def test_missing_metadata_adds_small_suspicion():
    """No EXIF at all adds a small baseline suspicion (not decisive)."""
    score, signals = get_ai_suspicion_score({}, 0, 0, 0)

    # Should be non-zero but below the confidence threshold
    assert 0 < score < 0.5
