"""
Static lookup tables and regex patterns used across the detection pipeline.

These constants are referenced by metadata_scorer.py and image_detector.py
to classify media based on known AI generator signatures.
"""

TIER_1_GENERATORS = [
    "midjourney", "dall-e", "dalle", "stable diffusion", "stablediffusion",
    "adobe firefly", "bing image creator", "flux", "black forest labs",
    "ideogram", "leonardo.ai", "leonardo", "runway", "gen-2", "gen-3",
    "luma", "dream machine", "kling", "kolors", "pika labs", "sora",
    "tensor.art", "seaart", "civitai", "playground ai", "recraft",
    "comfyui", "automatic1111", "invokeai", "easydiffusion",
    "foocus", "mj v6", "nijijourney", "img2img", "text2img",
    "generative fill", "generative expand", "trainedalgorithmicmedia",
    "compositeWithTrainedAlgorithmicMedia", "algorithmicmedia"
]

TIER_2_TECH_TERMS = [
    "latent", "hypernetwork", "lora", "denoising", "sampler",
    "cfg scale", "steps: ", "seed:", "clip skip", "controlnet",
    "inpainting", "outpainting", "prompt", "negative prompt",
    "synthetic", "deep learning", "neural network", "gan",
    "generated by", "created with ai", "imagined with"
]

TIER_3_REGEX = r"(?i)\b(ai|gpt|bot|gen)\b"

# Tags that indicate actual PHYSICAL human hardware provenance.
# If these are missing, the image is "Stripped" and goes to Gemini (if large).
# "Software", "XMP", or "Comments" are excluded because web tools add those.
PROVENANCE_WHITELIST = {
    "Make", "Model", "ExposureTime", "ISOSpeedRatings",
    "FNumber", "GPSLatitude", "GPSLongitude", "GPSAltitude",
    "BodySerialNumber", "LensSerialNumber", "LensModel", "Flash",
    "SubSecTimeOriginal", "SubSecTimeDigitized",
    "Orientation", "ColorSpace", "ExifOffset"
}
