"""
Top-level detection pipeline — public entry point for the /detect route.

`detect_ai_media` orchestrates:
  1. C2PA manifest check (cryptographic provenance — instant early exit)
  2. Video path  → metadata scoring → tri-frame Gemini batch
  3. Image path  → detect_ai_media_image_logic (metadata → Gemini)
"""

import os
import asyncio
import logging

from app.integrations.c2pa import get_c2pa_manifest
from app.integrations.gemini.client import analyze_batch_images_pro_turbo
from app.detection.hashing import get_smart_file_hash
from app.detection.cache import get_cached_result, set_cached_result
from app.detection.video_detector import (
    extract_video_frames,
    get_video_metadata,
    get_video_metadata_score,
)
from app.detection.image_detector import detect_ai_media_image_logic
from app.config import settings

logger = logging.getLogger(__name__)

VIDEO_EXTENSIONS = ('.mp4', '.mov', '.avi', '.mkv', '.webm', '.gif')


# ---------------------------------------------------------------------------
# C2PA provenance classification tables
#
# C2PA is NOT AI-only — real cameras (Leica M11-P, Sony α1/α9 III/α7 IV,
# Nikon Z6III, Canon, Fujifilm) and editing tools (Photoshop, Lightroom)
# also embed manifests.  We cannot rely on manifest existence alone.
#
# Strategy (three independent passes, first match wins):
#   Pass 1a — action label: c2pa.actions OR c2pa.actions.v2
#   Pass 1b — digitalSourceType contains an AI-specific IPTC term
#   Pass 1c — description or softwareAgent in any assertion
#   Pass 2  — claim_generator / claim_generator_info name fallback
# ---------------------------------------------------------------------------

# C2PA digitalSourceType URI fragments that indicate generative AI.
# Source: IPTC NewsCodes https://cv.iptc.org/newscodes/digitalsourcetype/
_AI_SOURCE_TYPES = (
    "trainedAlgorithmicMedia",             # fully AI-generated
    "compositeWithTrainedAlgorithmicMedia", # AI composite / inpainted
    "algorithmicMedia",                    # broad algorithmic generation
)

# Action description keywords that signal AI generation/editing.
_AI_ACTION_TERMS = (
    "generative fill", "ai-modified", "edited with ai",
    "ai generated", "ai-generated", "generated by ai",
)

# Known AI generator names matched case-insensitively against:
#   • claim_generator_info[*].name
#   • claim_generator (top-level string)
#   • assertion data.softwareAgent
#
# Sources:
#   OpenAI:      https://help.openai.com/en/articles/8912793-c2pa-in-dall-e-3
#   Azure OpenAI: https://learn.microsoft.com/azure/ai-foundry/openai/concepts/content-credentials
#                 softwareAgent = "Azure OpenAI DALL-E" | "Azure OpenAI ImageGen"
#   Google:       https://cloud.google.com/vertex-ai/generative-ai/docs/content-credentials
#                 app = "Google Media Processing Services"
#   Amazon:       https://aws.amazon.com/about-aws/whats-new/2024/09/content-credentials-amazon-titan-image-generator/
#   Adobe:        Firefly signs via Adobe Inc. certificate
#   Midjourney:   adopted C2PA for transparent labelling
#
# Real cameras that also embed C2PA but must NOT be flagged:
#   Sony (α1, α9 III, α1 II, α7 IV), Nikon (Z6III), Leica (M11-P, SL3-S),
#   Canon, Fujifilm — none of their generator strings appear below.
_KNOWN_AI_C2PA_GENERATORS = {
    # OpenAI / ChatGPT
    "chatgpt", "dall-e", "dall·e", "openai", "gpt-4o", "gpt-image",
    # Azure OpenAI (softwareAgent values from MS docs)
    "azure openai", "azure openai dall-e", "azure openai imagegen",
    # Google (Vertex AI Imagen + Gemini image models)
    "google media processing services", "imagen", "google deepmind",
    # Amazon Titan
    "amazon titan", "aws titan", "titan image generator",
    # Adobe
    "adobe firefly", "firefly",
    # Midjourney
    "midjourney",
    # Stability AI / Stable Diffusion
    "stable diffusion", "stability ai", "stability",
    # Other notable AI tools
    "kling", "runway", "sora", "ideogram", "leonardo", "flux",
    "pika", "haiper", "luma", "dream machine",
}

# Azure OpenAI sets description = "AI Generated Image" on every manifest.
_AI_DESCRIPTION_TERMS = ("ai generated image", "ai-generated image", "generated by ai")


async def detect_ai_media(file_path: str, trusted_metadata: dict = None) -> dict:
    """
    Final Optimized Consensus Engine.

    Args:
        file_path: Path to the media file.
        trusted_metadata: Optional sidecar metadata from a mobile device.
            Bypasses OS privacy stripping. Fields: Make, Model, Software,
            DateTime, width, height, fileSize, namingEntropy, isOriginalPath, etc.
    """
    l1_data = {
        "status": "not_found",
        "provider": None,
        "description": "No cryptographic signature found."
    }

    # --- Layer 1: C2PA cryptographic provenance check ---
    manifest = await asyncio.to_thread(get_c2pa_manifest, file_path)

    if manifest:
        gen_info = manifest.get("claim_generator_info", [])
        generator = (
            gen_info[0].get("name", "Unknown") if gen_info
            else manifest.get("claim_generator", "Unknown")
        )

        is_generative_ai = False

        # Collect ALL generator names — ChatGPT creates dual manifests so
        # gen_info may contain multiple entries (ChatGPT outer + DALL-E inner).
        generator_names = [e.get("name", "") for e in gen_info if e.get("name")]
        if not generator_names:
            fallback = manifest.get("claim_generator", "")
            if fallback:
                generator_names.append(fallback)
        generator = generator_names[0] if generator_names else "Unknown"

        assertions = manifest.get("assertions", [])

        # Pass 1 — action assertions (c2pa.actions v1 and v2).
        for assertion in assertions:
            label = assertion.get("label", "")
            if label in ("c2pa.actions", "c2pa.actions.v2"):
                actions = assertion.get("data", {}).get("actions", [])
                for action in actions:
                    source_type = action.get("digitalSourceType", "")
                    if any(t in source_type for t in _AI_SOURCE_TYPES):
                        is_generative_ai = True
                    desc = action.get("description", "").lower()
                    if any(term in desc for term in _AI_ACTION_TERMS):
                        is_generative_ai = True
            if is_generative_ai:
                break

        # Pass 1c — softwareAgent / description fields in any assertion.
        # Azure OpenAI sets softwareAgent="Azure OpenAI DALL-E" and
        # description="AI Generated Image" in the claim assertion.
        if not is_generative_ai:
            for assertion in assertions:
                data = assertion.get("data", {})
                agent = str(data.get("softwareAgent", "")).lower()
                desc = str(data.get("description", "")).lower()
                if any(ai in agent for ai in _KNOWN_AI_C2PA_GENERATORS):
                    is_generative_ai = True
                    logger.info("c2pa_ai_flagged", extra={
                        "action": "c2pa_ai_flagged",
                        "signal": "softwareAgent",
                        "value": agent[:80],
                    })
                    break
                if any(term in desc for term in _AI_DESCRIPTION_TERMS):
                    is_generative_ai = True
                    logger.info("c2pa_ai_flagged", extra={
                        "action": "c2pa_ai_flagged",
                        "signal": "description",
                        "value": desc[:60],
                    })
                    break

        # Pass 2 — generator name fallback.
        # Catches AI tools whose manifest doesn't use standard action labels
        # (e.g. ChatGPT, Google Imagen signing as "Google Media Processing Services").
        if not is_generative_ai:
            for name in generator_names:
                name_lower = name.lower()
                if any(ai in name_lower for ai in _KNOWN_AI_C2PA_GENERATORS):
                    is_generative_ai = True
                    logger.info("c2pa_ai_flagged", extra={
                        "action": "c2pa_ai_flagged",
                        "signal": "generator_name",
                        "value": name[:80],
                    })
                    break

        l1_data = {
            "status": "verified_ai" if is_generative_ai else "verified_human",
            "provider": generator,
            "description": (
                f"Verified AI signature found ({generator})."
                if is_generative_ai
                else "Verified human-captured content."
            )
        }

        logger.info("c2pa_result", extra={
            "action": "c2pa_result",
            "generator": generator,
            "is_generative_ai": is_generative_ai,
        })

        return {
            "summary": "AI-Generated" if is_generative_ai else "No AI Detected",
            "confidence_score": 1.0,
            "is_short_circuited": True,
            "evidence_chain": [
                {
                    "layer": "Metadata Check",
                    "status": "flagged" if is_generative_ai else "passed",
                    "label": "Origin Verified",
                    "detail": (
                        f"Confirmed AI-generated by {generator}."
                        if is_generative_ai else
                        f"Confirmed authentic — captured by {generator}."
                    )
                }
            ]
        }

    # --- Layer 2: Video vs Image routing ---
    is_video = file_path.lower().endswith(VIDEO_EXTENSIONS)

    if is_video:
        filename = os.path.basename(file_path)
        logger.info("pipeline_video_start", extra={"action": "pipeline_video_start", "media_file": filename})

        video_hash = await asyncio.to_thread(get_smart_file_hash, file_path)
        cached_video_result = await get_cached_result(video_hash)

        if cached_video_result:
            logger.info("cache_hit_video", extra={"action": "cache_hit_video"})
            return cached_video_result

        video_metadata = await get_video_metadata(file_path)
        human_score, ai_meta_score, meta_signals, early_exit = get_video_metadata_score(
            video_metadata, filename, file_path
        )

        logger.info("video_metadata_scored", extra={
            "action": "video_metadata_scored",
            "human_score": round(human_score, 2),
            "ai_score": round(ai_meta_score, 2),
            "early_exit": early_exit,
            "signals": meta_signals,
        })

        if early_exit == "human":
            logger.info("video_early_exit_human", extra={"action": "video_early_exit_human"})
            res = {
                "summary": "No AI Detected",
                "confidence_score": 0.99,
                "is_short_circuited": True,
                "evidence_chain": [
                {
                    "layer": "Metadata Check",
                    "status": "passed",
                    "label": "Origin Check",
                    "detail": f"Recording fingerprint matches a real camera ({meta_signals[0] if meta_signals else 'Camera/Phone'})."
                }
                ]
            }
            cached_version = res.copy()
            cached_version["is_cached"] = True
            await set_cached_result(video_hash, cached_version)
            return res

        if early_exit == "ai":
            logger.info("video_early_exit_ai", extra={"action": "video_early_exit_ai"})
            res = {
                "summary": "AI-Generated",
                "confidence_score": 0.99,
                "is_short_circuited": True,
                "evidence_chain": [
                {
                    "layer": "Metadata Check",
                    "status": "flagged",
                    "label": "Origin Check",
                    "detail": f"AI creation tool identified ({meta_signals[0] if meta_signals else 'Unknown'})."
                }
                ]
            }
            cached_version = res.copy()
            cached_version["is_cached"] = True
            await set_cached_result(video_hash, cached_version)
            return res

        logger.info("video_batch_start", extra={"action": "video_batch_start"})

        loop = asyncio.get_running_loop()
        frames, quality_rejected = await loop.run_in_executor(
            None, extract_video_frames, file_path
        )

        if not frames:
            return {
                "summary": "Analysis Failed",
                "confidence_score": 0.0,
                "is_short_circuited": False,
                "evidence_chain": [
                    {
                        "layer": "System",
                        "status": "warning",
                        "label": "Video Error",
                        "detail": "Could not extract frames from video."
                    }
                ]
            }

        logger.info("video_frames_extracted", extra={
            "action": "video_frames_extracted",
            "frame_count": len(frames),
            "quality_rejected": quality_rejected,
        })

        gemini_result = await loop.run_in_executor(
            None, analyze_batch_images_pro_turbo, frames
        )

        confidence = gemini_result.get("confidence", 0.0)
        explanation = gemini_result.get("explanation", "Analysis completed.")
        quality_context = gemini_result.get("quality_context", "Unknown")

        logger.info("video_gemini_batch", extra={
            "action": "video_gemini_batch",
            "confidence": confidence,
        })

        is_ai_likely = confidence > settings.ai_confidence_threshold
        summary = "Likely AI-Generated" if is_ai_likely else "Likely Authentic"
        final_conf = confidence if is_ai_likely else (1.0 - confidence)

        final_video_result = {
            "summary": summary,
            "confidence_score": final_conf,
            "gpu_time_ms": 0,
            "is_gemini_used": True,
            "is_short_circuited": False,
            "evidence_chain": [
                {
                    "layer": "Metadata Check",
                    "status": "warning",
                    "label": "Origin Check",
                    "detail": "No camera fingerprint found."
                },
                {
                    "layer": "Visual Context",
                    "status": "flagged" if is_ai_likely else "passed",
                    "label": "Visual Inspection",
                    "detail": explanation,
                    "context_quality": quality_context
                }
            ]
        }

        cached_version = final_video_result.copy()
        cached_version["is_cached"] = True
        await set_cached_result(video_hash, cached_version)

        return final_video_result

    # --- Image path ---
    return await detect_ai_media_image_logic(file_path, l1_data, trusted_metadata=trusted_metadata)
